export type UXProfileName =
  | "Clean Core"
  | "Quantum Slate"
  | "Neural Flow"
  | "Aurora Pulse"
  | "Cyber Matrix"
  | "Holographic Flux"
  | "Sentient Canvas";

export interface UXProfileConfig {
  name: UXProfileName;
  grid_motion: "smooth_layout_only" | "layout_plus_stagger" | "smooth_layout" | "none";
  stagger: boolean;
  ambient_orbs: boolean;
  neural_background: boolean;
  magnetic_effect: boolean | "light";
  card_tilt: boolean | number;
  glow_intensity: "low" | "medium" | "high" | "subtle";
  focus_mode: "opacity_only" | "desaturate" | "none";
  hero_animation: "soft" | "medium" | "none";
  background_shift: "slow_60s" | "none";
  mouse_radial_highlight: boolean;
  border_trace: boolean;
  card_glow: "medium" | "none";
  compact_density_mode: boolean;
  node_pulse: boolean;
  card_float: boolean;
  skeleton_morph: boolean;
  large_ambient_waves: boolean;
  background_color_shift: boolean;
  hover_glow: "medium" | "none";
  cyber_grid_overlay: boolean;
  high_priority_pulse: boolean;
  compact_data_wall: boolean;
  matrix_rain_dark_only: boolean;
  chromatic_hover_split: boolean;
  glass_fragment_entry: boolean;
  glitch_border: boolean;
  reactive_background_ripple: boolean;
  combined_layers: boolean;
  floating_ai_silhouettes: boolean;
  slow_drift_duration: "30s" | "none";
  low_opacity_background: boolean;
  blur_background_elements: boolean;
  no_glitch: boolean;
  no_tilt: boolean;
  subtle_glow: boolean;
}

export const uxProfiles: Record<UXProfileName, UXProfileConfig> = {
  "Clean Core": {
    name: "Clean Core",
    grid_motion: "smooth_layout_only",
    stagger: true,
    ambient_orbs: false,
    neural_background: false,
    magnetic_effect: false,
    card_tilt: false,
    glow_intensity: "low",
    focus_mode: "opacity_only",
    hero_animation: "soft",
    background_shift: "slow_60s",
    mouse_radial_highlight: false,
    border_trace: false,
    card_glow: "none",
    compact_density_mode: false,
    node_pulse: false,
    card_float: false,
    skeleton_morph: false,
    large_ambient_waves: false,
    background_color_shift: false,
    hover_glow: "none",
    cyber_grid_overlay: false,
    high_priority_pulse: false,
    compact_data_wall: false,
    matrix_rain_dark_only: false,
    chromatic_hover_split: false,
    glass_fragment_entry: false,
    glitch_border: false,
    reactive_background_ripple: false,
    combined_layers: false,
    floating_ai_silhouettes: false,
    slow_drift_duration: "none",
    low_opacity_background: false,
    blur_background_elements: false,
    no_glitch: false,
    no_tilt: false,
    subtle_glow: false,
  },
  "Quantum Slate": {
    name: "Quantum Slate",
    grid_motion: "layout_plus_stagger",
    stagger: true,
    ambient_orbs: true,
    neural_background: false,
    magnetic_effect: false,
    card_tilt: false,
    glow_intensity: "medium",
    focus_mode: "desaturate",
    hero_animation: "medium",
    background_shift: "none",
    mouse_radial_highlight: true,
    border_trace: true,
    card_glow: "medium",
    compact_density_mode: true,
    node_pulse: false,
    card_float: false,
    skeleton_morph: false,
    large_ambient_waves: false,
    background_color_shift: false,
    hover_glow: "none",
    cyber_grid_overlay: false,
    high_priority_pulse: false,
    compact_data_wall: false,
    matrix_rain_dark_only: false,
    chromatic_hover_split: false,
    glass_fragment_entry: false,
    glitch_border: false,
    reactive_background_ripple: false,
    combined_layers: false,
    floating_ai_silhouettes: false,
    slow_drift_duration: "none",
    low_opacity_background: false,
    blur_background_elements: false,
    no_glitch: false,
    no_tilt: false,
    subtle_glow: false,
  },
  "Neural Flow": {
    name: "Neural Flow",
    grid_motion: "smooth_layout",
    stagger: false,
    ambient_orbs: false,
    neural_background: true,
    magnetic_effect: "light",
    card_tilt: false,
    glow_intensity: "low",
    focus_mode: "none",
    hero_animation: "none",
    background_shift: "none",
    mouse_radial_highlight: false,
    border_trace: false,
    card_glow: "none",
    compact_density_mode: false,
    node_pulse: true,
    card_float: true,
    skeleton_morph: true,
    large_ambient_waves: false,
    background_color_shift: false,
    hover_glow: "none",
    cyber_grid_overlay: false,
    high_priority_pulse: false,
    compact_data_wall: false,
    matrix_rain_dark_only: false,
    chromatic_hover_split: false,
    glass_fragment_entry: false,
    glitch_border: false,
    reactive_background_ripple: false,
    combined_layers: false,
    floating_ai_silhouettes: false,
    slow_drift_duration: "none",
    low_opacity_background: false,
    blur_background_elements: false,
    no_glitch: false,
    no_tilt: false,
    subtle_glow: false,
  },
  "Aurora Pulse": {
    name: "Aurora Pulse",
    grid_motion: "none",
    stagger: false,
    ambient_orbs: false,
    neural_background: false,
    magnetic_effect: false,
    card_tilt: 3,
    glow_intensity: "low",
    focus_mode: "none",
    hero_animation: "none",
    background_shift: "none",
    mouse_radial_highlight: false,
    border_trace: true,
    card_glow: "none",
    compact_density_mode: false,
    node_pulse: false,
    card_float: false,
    skeleton_morph: false,
    large_ambient_waves: true,
    background_color_shift: true,
    hover_glow: "medium",
    cyber_grid_overlay: false,
    high_priority_pulse: false,
    compact_data_wall: false,
    matrix_rain_dark_only: false,
    chromatic_hover_split: false,
    glass_fragment_entry: false,
    glitch_border: false,
    reactive_background_ripple: false,
    combined_layers: false,
    floating_ai_silhouettes: false,
    slow_drift_duration: "none",
    low_opacity_background: false,
    blur_background_elements: false,
    no_glitch: false,
    no_tilt: false,
    subtle_glow: false,
  },
  "Cyber Matrix": {
    name: "Cyber Matrix",
    grid_motion: "none",
    stagger: false,
    ambient_orbs: false,
    neural_background: false,
    magnetic_effect: false,
    card_tilt: 8,
    glow_intensity: "high",
    focus_mode: "none",
    hero_animation: "none",
    background_shift: "none",
    mouse_radial_highlight: false,
    border_trace: false,
    card_glow: "none",
    compact_density_mode: false,
    node_pulse: false,
    card_float: false,
    skeleton_morph: false,
    large_ambient_waves: false,
    background_color_shift: false,
    hover_glow: "none",
    cyber_grid_overlay: true,
    high_priority_pulse: true,
    compact_data_wall: true,
    matrix_rain_dark_only: true,
    chromatic_hover_split: false,
    glass_fragment_entry: false,
    glitch_border: false,
    reactive_background_ripple: false,
    combined_layers: false,
    floating_ai_silhouettes: false,
    slow_drift_duration: "none",
    low_opacity_background: false,
    blur_background_elements: false,
    no_glitch: false,
    no_tilt: false,
    subtle_glow: false,
  },
  "Holographic Flux": {
    name: "Holographic Flux",
    grid_motion: "none",
    stagger: false,
    ambient_orbs: false,
    neural_background: false,
    magnetic_effect: false,
    card_tilt: 12,
    glow_intensity: "low",
    focus_mode: "none",
    hero_animation: "none",
    background_shift: "none",
    mouse_radial_highlight: false,
    border_trace: false,
    card_glow: "none",
    compact_density_mode: false,
    node_pulse: false,
    card_float: false,
    skeleton_morph: false,
    large_ambient_waves: false,
    background_color_shift: false,
    hover_glow: "none",
    cyber_grid_overlay: false,
    high_priority_pulse: false,
    compact_data_wall: false,
    matrix_rain_dark_only: false,
    chromatic_hover_split: true,
    glass_fragment_entry: true,
    glitch_border: true,
    reactive_background_ripple: true,
    combined_layers: true,
    floating_ai_silhouettes: false,
    slow_drift_duration: "none",
    low_opacity_background: false,
    blur_background_elements: false,
    no_glitch: false,
    no_tilt: false,
    subtle_glow: false,
  },
  "Sentient Canvas": {
    name: "Sentient Canvas",
    grid_motion: "none",
    stagger: false,
    ambient_orbs: false,
    neural_background: false,
    magnetic_effect: false,
    card_tilt: false,
    glow_intensity: "subtle",
    focus_mode: "none",
    hero_animation: "none",
    background_shift: "none",
    mouse_radial_highlight: false,
    border_trace: false,
    card_glow: "none",
    compact_density_mode: false,
    node_pulse: false,
    card_float: false,
    skeleton_morph: false,
    large_ambient_waves: false,
    background_color_shift: false,
    hover_glow: "none",
    cyber_grid_overlay: false,
    high_priority_pulse: false,
    compact_data_wall: false,
    matrix_rain_dark_only: false,
    chromatic_hover_split: false,
    glass_fragment_entry: false,
    glitch_border: false,
    reactive_background_ripple: false,
    combined_layers: false,
    floating_ai_silhouettes: true,
    slow_drift_duration: "30s",
    low_opacity_background: true,
    blur_background_elements: true,
    no_glitch: true,
    no_tilt: true,
    subtle_glow: true,
  },
};
